name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.1
  - pandas=1.5.3
  - scikit-learn=1.0.2
  - pytest=7.2.1
  - requests=2.28.2
  - fastapi=0.63.0
  - uvicorn=0.20.0
  - gunicorn=20.1.0
  - pip=20.3.3
  - git=2.30.2
